import type { Transaction } from './types';

function nowIso(offsetDays: number): string {
	const d = new Date();
	d.setDate(d.getDate() - offsetDays);
	return d.toISOString();
}

export const MOCK_DATASETS: Record<'standard' | 'standardOver' | 'flex' | 'flyer' | 'neighborhood', Transaction[]> = {
	standard: [
		{
			transactionId: 'std-1',
			transactionSequence: 1001,
			transactionType: 0,
			amount: 9.5,
			resultingBalance: 0,
			postedDate: nowIso(2),
			actualDate: nowIso(2),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-marycrest',
			locationName: 'Marycrest',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Standard Meal Plan',
			paymentSystemType: 0,
			transactionKey: 'std-1',
		},
		{
			transactionId: 'std-2',
			transactionSequence: 1002,
			transactionType: 0,
			amount: 12.25,
			resultingBalance: 0,
			postedDate: nowIso(3),
			actualDate: nowIso(3),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-emporium',
			locationName: 'The Emporium',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Standard Meal Plan',
			paymentSystemType: 0,
			transactionKey: 'std-2',
		},
		{
			transactionId: 'std-3',
			transactionSequence: 1003,
			transactionType: 0,
			amount: 7.75,
			resultingBalance: 0,
			postedDate: nowIso(5),
			actualDate: nowIso(5),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-vwk',
			locationName: 'VWK',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Standard Meal Plan',
			paymentSystemType: 0,
			transactionKey: 'std-3',
		},
		{
			transactionId: 'std-4',
			transactionSequence: 1004,
			transactionType: 0,
			amount: 10.4,
			resultingBalance: 0,
			postedDate: nowIso(7),
			actualDate: nowIso(7),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-blend',
			locationName: 'The Blend',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Standard Meal Plan',
			paymentSystemType: 0,
			transactionKey: 'std-4',
		},
		{
			transactionId: 'std-5',
			transactionSequence: 1005,
			transactionType: 0,
			amount: -3.0,
			resultingBalance: 0,
			postedDate: nowIso(8),
			actualDate: nowIso(8),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-marycrest',
			locationName: 'Marycrest',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Standard Meal Plan',
			paymentSystemType: 0,
			transactionKey: 'std-5',
		},
	],
	standardOver: [
		{
			transactionId: 'stdov-1',
			transactionSequence: 1101,
			transactionType: 0,
			amount: 1500.0,
			resultingBalance: 0,
			postedDate: nowIso(1),
			actualDate: nowIso(1),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-vwk',
			locationName: 'VWK',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Standard Meal Plan',
			paymentSystemType: 0,
			transactionKey: 'stdov-1',
		},
		{
			transactionId: 'stdov-2',
			transactionSequence: 1102,
			transactionType: 0,
			amount: 2100.0,
			resultingBalance: 0,
			postedDate: nowIso(2),
			actualDate: nowIso(2),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-marycrest',
			locationName: 'Marycrest',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Standard Meal Plan',
			paymentSystemType: 0,
			transactionKey: 'stdov-2',
		},
		{
			transactionId: 'stdov-3',
			transactionSequence: 1103,
			transactionType: 0,
			amount: 120.0,
			resultingBalance: 0,
			postedDate: nowIso(3),
			actualDate: nowIso(3),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-blend',
			locationName: 'The Blend',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Standard Meal Plan',
			paymentSystemType: 0,
			transactionKey: 'stdov-3',
		},
	],
	flex: [
		{
			transactionId: 'flex-1',
			transactionSequence: 2001,
			transactionType: 0,
			amount: 11.0,
			resultingBalance: 0,
			postedDate: nowIso(1),
			actualDate: nowIso(1),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-vwk',
			locationName: 'VWK',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Flex Plan',
			paymentSystemType: 0,
			transactionKey: 'flex-1',
		},
		{
			transactionId: 'flex-2',
			transactionSequence: 2002,
			transactionType: 0,
			amount: 8.95,
			resultingBalance: 0,
			postedDate: nowIso(2),
			actualDate: nowIso(2),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-artstreet',
			locationName: 'Art Street',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Flex Plan',
			paymentSystemType: 0,
			transactionKey: 'flex-2',
		},
		{
			transactionId: 'flex-3',
			transactionSequence: 2003,
			transactionType: 0,
			amount: 13.5,
			resultingBalance: 0,
			postedDate: nowIso(4),
			actualDate: nowIso(4),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-toss',
			locationName: 'Toss',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Flex Plan',
			paymentSystemType: 0,
			transactionKey: 'flex-3',
		},
		{
			transactionId: 'flex-4',
			transactionSequence: 2004,
			transactionType: 0,
			amount: 6.25,
			resultingBalance: 0,
			postedDate: nowIso(6),
			actualDate: nowIso(6),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-blend-express',
			locationName: 'The Blend Express',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Flex Plan',
			paymentSystemType: 0,
			transactionKey: 'flex-4',
		},
		{
			transactionId: 'flex-5',
			transactionSequence: 2005,
			transactionType: 0,
			amount: 15.75,
			resultingBalance: 0,
			postedDate: nowIso(9),
			actualDate: nowIso(9),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-abp',
			locationName: 'Au Bon Pain',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Flex Plan',
			paymentSystemType: 0,
			transactionKey: 'flex-5',
		},
		{
			transactionId: 'flex-6',
			transactionSequence: 2006,
			transactionType: 0,
			amount: -2.0,
			resultingBalance: 0,
			postedDate: nowIso(10),
			actualDate: nowIso(10),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-abp',
			locationName: 'Au Bon Pain',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Flex Plan',
			paymentSystemType: 0,
			transactionKey: 'flex-6',
		},
	],
	neighborhood: [
		{
			transactionId: 'neigh-1',
			transactionSequence: 4001,
			transactionType: 0,
			amount: 12.0,
			resultingBalance: 0,
			postedDate: nowIso(1),
			actualDate: nowIso(1),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-artstreet',
			locationName: 'Art Street',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Neighborhood Plan',
			paymentSystemType: 0,
			transactionKey: 'neigh-1',
		},
		{
			transactionId: 'neigh-2',
			transactionSequence: 4002,
			transactionType: 0,
			amount: 9.5,
			resultingBalance: 0,
			postedDate: nowIso(2),
			actualDate: nowIso(2),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-toss',
			locationName: 'Toss',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Neighborhood Plan',
			paymentSystemType: 0,
			transactionKey: 'neigh-2',
		},
		{
			transactionId: 'neigh-3',
			transactionSequence: 4003,
			transactionType: 0,
			amount: 15.0,
			resultingBalance: 0,
			postedDate: nowIso(3),
			actualDate: nowIso(3),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-emporium',
			locationName: 'The Emporium',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Neighborhood Plan',
			paymentSystemType: 0,
			transactionKey: 'neigh-3',
		},
		{
			transactionId: 'neigh-4',
			transactionSequence: 4004,
			transactionType: 0,
			amount: -1.25,
			resultingBalance: 0,
			postedDate: nowIso(4),
			actualDate: nowIso(4),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-artstreet',
			locationName: 'Art Street',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Neighborhood Plan',
			paymentSystemType: 0,
			transactionKey: 'neigh-4',
		},
	],
	flyer: [
		{
			transactionId: 'flyer-1',
			transactionSequence: 3001,
			transactionType: 0,
			amount: 5.0,
			resultingBalance: 0,
			postedDate: nowIso(1),
			actualDate: nowIso(1),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-marycrest',
			locationName: 'Marycrest',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Flyer Express',
			paymentSystemType: 0,
			transactionKey: 'flyer-1',
		},
		{
			transactionId: 'flyer-2',
			transactionSequence: 3002,
			transactionType: 0,
			amount: 7.25,
			resultingBalance: 0,
			postedDate: nowIso(2),
			actualDate: nowIso(2),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-emporium',
			locationName: 'The Emporium',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Flyer Express',
			paymentSystemType: 0,
			transactionKey: 'flyer-2',
		},
		{
			transactionId: 'flyer-3',
			transactionSequence: 3003,
			transactionType: 0,
			amount: 4.75,
			resultingBalance: 0,
			postedDate: nowIso(3),
			actualDate: nowIso(3),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-blend',
			locationName: 'The Blend',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Flyer Express',
			paymentSystemType: 0,
			transactionKey: 'flyer-3',
		},
		{
			transactionId: 'flyer-4',
			transactionSequence: 3004,
			transactionType: 0,
			amount: -1.5,
			resultingBalance: 0,
			postedDate: nowIso(4),
			actualDate: nowIso(4),
			patronId: 'mock-patron',
			planId: 'mock-plan',
			tenderId: 'mock-tender',
			locationId: 'loc-marycrest',
			locationName: 'Marycrest',
			patronFullName: 'Mock User',
			accountType: 0,
			accountName: 'Flyer Express',
			paymentSystemType: 0,
			transactionKey: 'flyer-4',
		},
	],
};

// Back-compat: keep the old helper but return deterministic data
export function buildMockTransactions(kind: 'standard' | 'standardOver' | 'flex' | 'flyer' | 'neighborhood'): Transaction[] {
	return MOCK_DATASETS[kind];
}